notifications:
 email: true

language: c++

matrix:
  include:
    - os: linux
      services:
      - postgres
      addons:
        postgresql: "10"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libpq5
            - libpq-dev
      env:
        global:
          - PGPORT=5432
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo service postgresql restart

before_script:
  - psql -f ./setup_psql_db.sql -U postgres
  - psql -f ./table_creation.sql -U postgres -d amouroug

script:
  - make -j$(cat /proc/cpuinfo | grep processor | tail -1| cut -d":" -f2)
  - build/app/shape_data_app/shape_data_app --bnd-dir ./data_files/ --rtc-dir ./data_files/
  - build/app/shape_data_app/shape_data_app --search Illinois
  - build/app/shape_data_app/shape_data_app --search Atlanta
  - build/app/shape_data_app/shape_data_app --search DeKalb
  - build/app/shape_data_app/shape_data_app --search Lithonia
  - build/app/shape_data_app/shape_data_app --search Kalb --contains
