notifications:
 email: true

language: c++

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libpq5
            - libpq-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        postgresql: "10"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libpq5
            - libpq-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - make all