notifications:
 email: true

language: c++

matrix:
  include:
    - os: linux
      services:
      - postgres
      addons:
        postgresql: "10"
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libpq5
            - libpq-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
  - psql -c "create user amouroug with encrypted password 'FullMetalAlchemist#8';" -U postgres
  - psql -c "ALTER USER amouroug WITH SUPERUSER CREATEDB CREATEROLE;" -U postgres
  - psql -f ./setup_psql_db.sql -U postgres

script:
  - make 
  - build/app/serialize_shape_data/serialize_shape_data --bnd-dir ./data_files/ --rtc-dir ./data_files/
