# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".typo-ci.yml"
  - "*.sql"
  - "Makefile"
  - ".gitignore"
  - "data_file/**"
  - ".travis.yml"

# Any typos we should ignore?
excluded_words:
  - typoci
