DROP SCHEMA IF EXISTS amouroug CASCADE;
CREATE SCHEMA amouroug;
CREATE USER amouroug WITH PASSWORD 'FullMetalAlchemist#8';
ALTER USER amouroug WITH SUPERUSER CREATEDB CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE amouroug TO amouroug;
CREATE TABLE amouroug.STATE(ID INT PRIMARY KEY, IName VARCHAR(50), Min_Latitude VARCHAR(10), Max_Latitude VARCHAR(10), Min_Longitude VARCHAR(10), Max_Longitude VARCHAR(10));
CREATE TABLE amouroug.COUNTY(ID INT PRIMARY KEY, IName VARCHAR(50), Min_Latitude VARCHAR(10), Max_Latitude VARCHAR(10), Min_Longitude VARCHAR(10), Max_Longitude VARCHAR(10));
CREATE TABLE  amouroug.PLACE(ID INT PRIMARY KEY, IName VARCHAR(50), Min_Latitude VARCHAR(10), Max_Latitude VARCHAR(10), Min_Longitude VARCHAR(10), Max_Longitude VARCHAR(10));
CREATE TABLE  amouroug.SUBCOUNTY(ID INT PRIMARY KEY, IName VARCHAR(50), Min_Latitude VARCHAR(10), Max_Latitude VARCHAR(10), Min_Longitude VARCHAR(10), Max_Longitude VARCHAR(10));
