DROP DATABASE IF EXISTS amouroug CASCADE;
CREATE DATABASE amouroug;
CREATE USER amouroug WITH PASSWORD 'FullMetalAlchemist#8';
ALTER USER amouroug WITH SUPERUSER CREATEDB CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE amouroug TO amouroug;
